services:

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: loadtest
    ports:
      - "5432:5432"

  gateway:
    build: ./services/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres

  worker:
    build: ./services/load-tester
    depends_on:
      - redis
      - postgres

  metrics-processor:
    build: ./services/metrics-processor
    depends_on:
      - redis
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1